function pos_ee_num = kinematic_structure_evaluator_num(in1)
%KINEMATIC_STRUCTURE_EVALUATOR_NUM
%    POS_EE_NUM = KINEMATIC_STRUCTURE_EVALUATOR_NUM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Apr-2023 13:22:01

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t10 = sin(q4);
t11 = sin(q5);
pos_ee_num = reshape([t2,t2+t3,t2+t3+t4,t2+t3+t4+t5,t2+t3+t4+t5+t6,t2+t3+t4+t5+t6+cos(q6),t7,t7+t8,t7+t8+t9,t7+t8+t9+t10,t7+t8+t9+t10+t11,t7+t8+t9+t10+t11+sin(q6),q1,q2,q3,q4,q5,q6],[6,3]);
