function pos_ee = kinematic_structure_evaluator(in1,in2)
%KINEMATIC_STRUCTURE_EVALUATOR
%    POS_EE = KINEMATIC_STRUCTURE_EVALUATOR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Apr-2023 13:22:00

L1 = in2(:,1);
L2 = in2(:,2);
L3 = in2(:,3);
L4 = in2(:,4);
L5 = in2(:,5);
L6 = in2(:,6);
q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t10 = sin(q4);
t11 = sin(q5);
t12 = L1.*t2;
t13 = L2.*t3;
t14 = L3.*t4;
t15 = L4.*t5;
t16 = L5.*t6;
t17 = L1.*t7;
t18 = L2.*t8;
t19 = L3.*t9;
t20 = L4.*t10;
t21 = L5.*t11;
pos_ee = reshape([t12,t12+t13,t12+t13+t14,t12+t13+t14+t15,t12+t13+t14+t15+t16,t12+t13+t14+t15+t16+L6.*cos(q6),t17,t17+t18,t17+t18+t19,t17+t18+t19+t20,t17+t18+t19+t20+t21,t17+t18+t19+t20+t21+L6.*sin(q6),q1,q2,q3,q4,q5,q6],[6,3]);
