function pos_ee = pos_ee4_evaluator(L1,L2,L3,L4,q1,q2,q3,q4)
%POS_EE4_EVALUATOR
%    POS_EE = POS_EE4_EVALUATOR(L1,L2,L3,L4,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Apr-2023 13:21:59

pos_ee = [L1.*cos(q1)+L2.*cos(q2)+L3.*cos(q3)+L4.*cos(q4),L1.*sin(q1)+L2.*sin(q2)+L3.*sin(q3)+L4.*sin(q4),q4];
