function pos_cm = pos_cm5_evaluator(L1,L2,L3,L4,L5,q1,q2,q3,q4,q5)
%POS_CM5_EVALUATOR
%    POS_CM = POS_CM5_EVALUATOR(L1,L2,L3,L4,L5,Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Apr-2023 13:22:00

pos_cm = [L1.*cos(q1)+L2.*cos(q2)+L3.*cos(q3)+L4.*cos(q4)+(L5.*cos(q5))./2.0,L1.*sin(q1)+L2.*sin(q2)+L3.*sin(q3)+L4.*sin(q4)+(L5.*sin(q5))./2.0,q5];
