function error_front = error_front_evaluator(in1,in2,in3)
%ERROR_FRONT_EVALUATOR
%    ERROR_FRONT = ERROR_FRONT_EVALUATOR(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Apr-2023 13:32:51

goalx1 = in3(:,1);
goaly1 = in3(:,2);
s14 = in1(4);
s15 = in1(5);
s16 = in1(6);
s24 = in1(10);
s25 = in1(11);
s26 = in1(12);
sigma1 = in2(1,:);
sigma2 = in2(2,:);
t2 = s14.*sigma1;
t3 = s15.*sigma1;
t4 = s16.*sigma1;
t5 = s24.*sigma2;
t6 = s25.*sigma2;
t7 = s26.*sigma2;
t8 = pi.*(3.0./2.0);
t9 = pi.*(5.0./4.0);
t10 = pi.*(7.0./4.0);
t11 = t2+t5+t9;
t12 = t2+t3+t5+t6+t10;
t13 = t2+t3+t4+t5+t6+t7+t8;
error_front = [-goalx1+cos(t11).*1.5e+2+cos(t12).*1.3e+2+cos(t13).*7.5e+1+2.5e+2,-goaly1+sin(t11).*1.5e+2+sin(t12).*1.3e+2+sin(t13).*7.5e+1];
