function error_tot = error_tot_evaluator(in1,in2,in3)
%ERROR_TOT_EVALUATOR
%    ERROR_TOT = ERROR_TOT_EVALUATOR(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Apr-2023 13:32:51

goalx1 = in3(:,1);
goalx2 = in3(:,3);
goaly1 = in3(:,2);
goaly2 = in3(:,4);
s11 = in1(1);
s12 = in1(2);
s13 = in1(3);
s14 = in1(4);
s15 = in1(5);
s16 = in1(6);
s21 = in1(7);
s22 = in1(8);
s23 = in1(9);
s24 = in1(10);
s25 = in1(11);
s26 = in1(12);
sigma1 = in2(1,:);
sigma2 = in2(2,:);
t2 = s11.*sigma1;
t3 = s12.*sigma1;
t4 = s13.*sigma1;
t5 = s14.*sigma1;
t6 = s15.*sigma1;
t7 = s16.*sigma1;
t8 = s21.*sigma2;
t9 = s22.*sigma2;
t10 = s23.*sigma2;
t11 = s24.*sigma2;
t12 = s25.*sigma2;
t13 = s26.*sigma2;
t14 = pi.*(3.0./2.0);
t15 = pi.*(5.0./4.0);
t16 = pi.*(7.0./4.0);
t17 = pi.*(1.3e+1./4.0);
t18 = t5+t11+t15;
t19 = t4+t10+t16;
t20 = t5+t6+t11+t12+t16;
t21 = t3+t4+t9+t10+t17;
t22 = t2+t3+t4+t8+t9+t10+t14;
t23 = t5+t6+t7+t11+t12+t13+t14;
error_tot = [-goalx1+cos(t18).*1.5e+2+cos(t20).*1.3e+2+cos(t23).*7.5e+1+2.5e+2,-goaly1+sin(t18).*1.5e+2+sin(t20).*1.3e+2+sin(t23).*7.5e+1,-goalx2+cos(t19).*1.5e+2+cos(t21).*1.3e+2+cos(t22).*7.5e+1-2.5e+2,-goaly2+sin(t19).*1.5e+2+sin(t21).*1.3e+2+sin(t22).*7.5e+1];
