function J_back = J_back_evaluator(in1,in2)
%J_back_evaluator
%    J_back = J_back_evaluator(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Apr-2023 13:32:49

s11 = in1(1);
s12 = in1(2);
s13 = in1(3);
s21 = in1(7);
s22 = in1(8);
s23 = in1(9);
sigma1 = in2(1,:);
sigma2 = in2(2,:);
t2 = s12+s13;
t3 = s22+s23;
t4 = s11.*sigma1;
t5 = s12.*sigma1;
t6 = s13.*sigma1;
t7 = s21.*sigma2;
t8 = s22.*sigma2;
t9 = s23.*sigma2;
t12 = pi.*(3.0./2.0);
t13 = pi.*(7.0./4.0);
t14 = pi.*(1.3e+1./4.0);
t10 = s11+t2;
t11 = s21+t3;
t15 = t6+t9+t13;
t18 = t5+t6+t8+t9+t14;
t21 = t4+t5+t6+t7+t8+t9+t12;
t16 = sin(t15);
t17 = cos(t15);
t19 = cos(t18);
t20 = sin(t18);
t22 = cos(t21);
t23 = sin(t21);
J_back = reshape([s13.*t16.*-1.5e+2-t2.*t20.*1.3e+2-t10.*t23.*7.5e+1,s13.*t17.*1.5e+2+t2.*t19.*1.3e+2+t10.*t22.*7.5e+1,s23.*t16.*-1.5e+2-t3.*t20.*1.3e+2-t11.*t23.*7.5e+1,s23.*t17.*1.5e+2+t3.*t19.*1.3e+2+t11.*t22.*7.5e+1],[2,2]);
