function J_front = J_front_evaluator(in1,in2)
%J_front_evaluator
%    J_front = J_front_evaluator(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    24-Apr-2023 13:32:49

s14 = in1(4);
s15 = in1(5);
s16 = in1(6);
s24 = in1(10);
s25 = in1(11);
s26 = in1(12);
sigma1 = in2(1,:);
sigma2 = in2(2,:);
t2 = s14+s15;
t3 = s24+s25;
t4 = s14.*sigma1;
t5 = s15.*sigma1;
t6 = s16.*sigma1;
t7 = s24.*sigma2;
t8 = s25.*sigma2;
t9 = s26.*sigma2;
t12 = pi.*(3.0./2.0);
t13 = pi.*(5.0./4.0);
t14 = pi.*(7.0./4.0);
t10 = s16+t2;
t11 = s26+t3;
t15 = t4+t7+t13;
t18 = t4+t5+t7+t8+t14;
t21 = t4+t5+t6+t7+t8+t9+t12;
t16 = sin(t15);
t17 = cos(t15);
t19 = cos(t18);
t20 = sin(t18);
t22 = cos(t21);
t23 = sin(t21);
J_front = reshape([s14.*t16.*-1.5e+2-t2.*t20.*1.3e+2-t10.*t23.*7.5e+1,s14.*t17.*1.5e+2+t2.*t19.*1.3e+2+t10.*t22.*7.5e+1,s24.*t16.*-1.5e+2-t3.*t20.*1.3e+2-t11.*t23.*7.5e+1,s24.*t17.*1.5e+2+t3.*t19.*1.3e+2+t11.*t22.*7.5e+1],[2,2]);
