function J_tot_q = J_tot_evaluator_q(in1)
%J_tot_evaluator_q
%    J_tot_q = J_tot_evaluator_q(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    24-Apr-2023 22:19:24

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
q5 = in1(5,:);
q6 = in1(6,:);
t2 = pi.*(3.0./2.0);
t3 = pi.*(5.0./4.0);
t4 = pi.*(7.0./4.0);
t5 = pi.*(1.3e+1./4.0);
t6 = q4+t3;
t7 = q3+t4;
t8 = q4+q5+t4;
t10 = q1+q2+q3+t2;
t11 = q4+q5+q6+t2;
t13 = q2+q3+t5;
t9 = cos(t8);
t12 = sin(t8);
t14 = cos(t13);
t15 = sin(t13);
t16 = cos(t10);
t17 = cos(t11);
t18 = sin(t10);
t19 = sin(t11);
t20 = t9.*1.3e+2;
t21 = t12.*1.3e+2;
t22 = t16.*7.5e+1;
t23 = t17.*7.5e+1;
t24 = t18.*7.5e+1;
t25 = t19.*7.5e+1;
t26 = t14.*1.3e+2;
t28 = t15.*1.3e+2;
t27 = -t21;
t29 = -t24;
t30 = -t25;
t31 = -t28;
J_tot_q = reshape([0.0,0.0,t29,t22,0.0,0.0,t29+t31,t22+t26,0.0,0.0,t29+t31-sin(t7).*1.5e+2,t22+t26+cos(t7).*1.5e+2,t27+t30-sin(t6).*1.5e+2,t20+t23+cos(t6).*1.5e+2,0.0,0.0,t27+t30,t20+t23,0.0,0.0,t30,t23,0.0,0.0],[4,6]);
